---
title: "Internet Appendix"
author: "Kalmenovitz, Lowry, Volkova"
date: "2021-11-20"
output:
  word_document: 
    fig_caption: yes
    fig_height: 3.65
    fig_width: 7.5
    reference_docx: /Users/evolkova/Dropbox/style_reference.docx
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
fontsize: 10pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

require(ggplot2)
require(data.table)
require(lubridate)
require(ggthemes)
require(dplyr)
require(RColorBrewer)
require(rmarkdown)
require(knitr)

require(modelsummary)
require(fixest)
require(flextable)
require(psych)
require(wordcloud)

path <- "/Users/evolkova/Dropbox/Projects/Govt Agenda/"

temp_path <- path %>%
  paste0("Sandbox/20201029/temp_files/")

data_path <- path %>%
  paste0("/Data/")

th1 <- function() {
  theme(axis.line = element_line(size=rel(1), colour = "black"), 
        panel.grid.major = element_line(colour = "#d3d3d3"), 
        panel.grid.minor = element_blank(), 
        panel.border = element_blank(), panel.background = element_blank(),
        plot.title = element_text(size = rel(1.5), family = "Calibri", face = "bold"),
        text=element_text(family="Calibri"), 
        axis.text.x=element_text(colour="black", size = rel(1.3)),
        axis.title.x = element_text(colour="black", size = rel(1.3)),
        axis.title.y = element_text(colour="black", size = rel(1.3)),
        axis.text.y=element_text(colour="black", size = rel(1.4))) +
    theme(plot.title = element_text(hjust = 0.5))
}

th <- function() {
  theme_minimal() + 
  theme(legend.position='bottom', text=element_text(family="Georgia")) +
  theme(legend.title = element_text(size = rel(0.75)), 
        legend.text = element_text(size = rel(0.75)))  
}


topics.prob.all <- readRDS(paste0(temp_path, "topics.prob.rds"))
topics.prob <- topics.prob.all[!duplicated(document_number)]

tmp <- topics.prob
for(i in 1:100) tmp[[i]] <- tmp[[i]]*topics.prob$nwords

topiccols <- c(1:100, "nwords")
topics.prob.yeartype <- tmp[, lapply(.SD, . %>% sum), by = .(type,year), .SDcols = topiccols]
topics.prob.year <- tmp[, lapply(.SD, . %>% sum), by = .(year), .SDcols = topiccols]


### load topic to agency
topicstoagencies <- temp_path %>%
  paste0("topicagencyyear.csv") %>%
  fread

### load company year data
companyyear <- "companyyear.rds" %>% 
  paste0(data_path,.) %>%
  readRDS

wordcloudlist <- "wordcloudlist.rds" %>% 
  paste0(temp_path,.) %>%
  readRDS

labels <- "./Data/topic_labels_ML_KV_JK.csv" %>%
  paste0(path,.) %>% 
  fread

companyyear[, `:=`(log_sale = log(1 + sale), 
                   fcf_at = fcf/at,
                   LogWords10K = log(Words10K))]

vars <- c("log_sale", "ppe_at", "ebitda_at", "sale",
          "growth", "tobin", 
          "regul.disp_Notice", "regul.complex_Notice", "regul.complex_Notice.log",  
          "regul.disp_PRule", "regul.complex_PRule", "regul.complex_PRule.log",  
          "regul.disp_Rule", "regul.complex_Rule", "regul.complex_Rule.log", 
          "regul.disp_RIN", "regul.complex_RIN", "regul.complex_RIN.log", 
          "regul.disp_old_RIN", "regul.complex_old_RIN", "regul.complex_old_RIN.log", 
          "regul.disp", "regul.complex", "regul.complex.log", 
          "regul.disp.group.JK", "regul.disp.group.KV", 
          "regul.complex.log.group.JK", "regul.complex.log.group.KV",
          "topic.disp", "LogWords10K",
          "lead.sga_at", "lead.capx_at", "lead.inv_at", "lead.emp_at", 
          "lead.leverage", "lead.growth", "lead.roa", "lead.cash_at", "lead.growth.at") 

controls_min <- " +  regul.complex.log + LogWords10K + ppe_at + ebitda_at + 
 log_sale + tobin" 

col <- which(colnames(companyyear) %in% vars)
ind <- companyyear$sale > 0

for(c in col) {
  ind <- ind & !is.na(companyyear[[c]]) & !is.nan(companyyear[[c]]) & !is.infinite(companyyear[[c]])
}

companyyear <- companyyear[ind]
companyyear[, lead.roa := 100*lead.roa]
companyyear[, roa := 100*roa]

win <- function(x, eps = 0.005){
  up <- quantile(x, na.rm = T, 1 - eps)
  down <- quantile(x, na.rm = T, eps)
  x[x>up] <- up
  x[x<down] <- down
  return(x)
}

for(c in col) companyyear[[c]] <- win(companyyear[[c]])

companyyear$lead.tfp <- win(companyyear$lead.tfp)
### here we correct coefficients names
cm <- c("regul.disp" = "Regulation Dispersion",
        "topic.disp" = "Topic Dispersion",
        "regul.complex.log" = "Regulation Complexity",
        "LogWords10K" = "Log(Word,10K)",
        "Nsegments" = "Nsegments",
        "ppe_at" = "PPE/AT",
        "ebitda_at" = "EBITDA/AT", 
        "emp_sale" = "Emp/Sale",
        "log_sale" = "Log(Sale)",
        "log_at" = "log(AT)",
        "growth" = "Sales Growth",
        "tobin" = "Tobin's Q",
        "fcf_at" = "FCF to AT",
        "(Intercept)" = "(Intercept)")

### here we correct the names
  mapagency <- data.table(agency = "environmental protection agency", label = "EPA") %>%
    rbind(list("department of health and human services", "DHHS")) %>%
    rbind(list("department of transportation", "Transportation")) %>%
    rbind(list("department of commerce","Commerce")) %>%
    rbind(list("securities and exchange commission", "SEC")) %>%
    rbind(list("department of interior", "DOI")) %>%
    rbind(list("department of agriculture", "USDA")) %>%
    rbind(list("department of energy", "DOE")) %>%
    rbind(list("department of labor", "DOL")) %>%
    rbind(list("department of treasury", "Treasury")) %>%
    rbind(list("department of justice", "DOJ")) %>%
    rbind(list("nuclear regulatory commission", "NRC")) %>%
    rbind(list("federal communications commission", "FCC")) %>%
    rbind(list("department of housing and urban developm", "HUD")) %>%
    rbind(list("federal reserve system", "FRS")) %>%
    rbind(list("international trade commission", "ITC")) %>% 
    rbind(list("federal energy regulatory commission", "FERC")) %>%
    rbind(list("commodity futures trading commission", "CFTC")) %>%
    rbind(list("department of veteran affairs", "DVA"))

  
topicagencyyear <- "./Data/topicagencyyear.csv" %>% 
  paste0(path,.) %>% 
  fread()

agencydisp <- topicagencyyear[,list(AgencyDisp = 1 - sum(AgencyPercent^2)),
                              by = "TopicNumber,year"]
  
ff12labels <- "./Data/Indlabels12.txt" %>%
  paste0(path,.) %>%
  readLines
setkey(mapagency, agency)

labels <- fread("/Users/evolkova/Dropbox/Projects/Govt Agenda/Data/topic_labels_ML_KV_JK.csv")

```



**Figure A1**

```{r fig2Ai, results = "asis", dpi = 300}
data <- topics.prob.year

top10topics <- function(data)
{
  data <- data %>%
  select("year", as.character(1:100)) %>%
  melt(id.vars = "year")

  colnames(data) <- c("year", "topic", "words")
  topic.words <- data[, list(words = sum(words)), by = topic]
  topic.words <- topic.words[order(words, decreasing = T)]

  toptopic <- topic.words$topic[1:10]

  data <- data[topic %in% toptopic]
  data[, cumwords := - sum(words), by = topic]
  setkey(data, cumwords, year)

  data$label <- labels[match(data$topic, labels$Topic)]$ShortLabel
  data[, label := paste0(topic, ": ", label)]
  data$label <- factor(data$label, levels = unique(data$label))

  plot <- ggplot(data, aes(x = year, y = words, fill = label)) + 
        geom_bar(stat = "identity", position = "stack") + 
        ylab("Words in Federal Register") + 
        th() + theme(axis.title.x=element_blank()) + 
        theme(legend.text = element_text(size = 8)) +
        theme(legend.title = element_text(size = 8, angle = 90,hjust = 0.5)) + 
        theme(legend.margin=margin(t = -0.3, unit='cm')) + 
        guides(fill=guide_legend(title="Topics:", ncol = 4)) + 
        scale_fill_brewer(palette = "Paired")

  return(plot)
}
cat("*Panel Ai: Distribution across top10 topics*")
topics.prob.year %>% 
  top10topics %>%
  print

cat("*Panel Aii: Distribution across top10 topics, notices only*") 
topics.prob.yeartype[type == "Notice"] %>% 
  top10topics %>%
  print
```

\newpage

```{r fig2Aiii, results = "asis", dpi = 300}
cat("*Panel Aiii: Distribution across top10 topics, proposed rules only*")
topics.prob.yeartype[type == "Proposed Rule"] %>% 
  top10topics %>%
  print

cat("*Panel Aiv: Distribution across top10 topics, rules only*")
topics.prob.yeartype[type == "Rule"] %>% 
  top10topics %>%
  print
```


**Figure A2**

```{r fig3a, results = "asis", dpi = 300}
reds <- c("#CF2213", "#B01111", "#811016")
blues <- c("blue", "navy", "#436FC2")
data <- topics.prob.year %>%
  select("year", as.character(1:100)) %>%
  melt(id.var = "year")

colnames(data) <- c("year", "topic", "words")

data$label <- labels[match(data$topic, labels$Topic)]$ShortLabel
data$label <- factor(data$label, levels = unique(data$label))



increases <- data[, list(change = words[.N] - words[1]), by = topic]
setkey(increases, change)
increases[, rank := 1:.N]
data$rank <- increases$rank[match(data$topic, increases$topic)]


plot <- ggplot(data[rank %in% 4:97], aes(x = year, y = words, fill = "grey")) + 
  geom_line(alpha = 0.3, aes(group = topic), size = 0.1) + 
  geom_line(data = data[rank == 100], size = 0.5, color = reds[1], aes(group = topic)) + 
  geom_line(data = data[rank == 99], size = 0.5, color = reds[2], aes(group = topic), linetype = "dashed") + 
  geom_line(data = data[rank == 98], size = 0.5, color = reds[3], aes(group = topic),linetype = "dotdash") + 
  geom_line(data = data[rank == 1], size = 0.5, color = blues[1], aes(group = topic)) + 
  geom_line(data = data[rank == 2], size = 0.5, color = blues[2], aes(group = topic), linetype = "dashed") + 
  geom_line(data = data[rank == 3], size = 0.5, color = blues[3], aes(group = topic),linetype = "dotdash") + ylab("Words in Federal Register") + 
  th() + theme(axis.title.x=element_blank()) + 
  theme(legend.position = "none") #+ 
  #ggtitle("Topics with Highest Increase/Decrease between 1995 and 2019")

p1 <- plot + geom_text(data = data %>% filter(rank == 100, year == 2016), nudge_x = 0.25, vjust = -1, size = 2.5, aes(label = paste0("T",topic)), color = reds[1]) + 
  geom_text(data = data %>% filter(rank == 99, year == 2016), nudge_x = -0.25, vjust = -1, size = 2.5, aes(label = paste0("T",topic)), color = reds[2]) + 
  geom_text(data = data %>% filter(rank == 98, year == 2016), nudge_x = 0.0, vjust = -1, size = 2.5, aes(label = paste0("T",topic)), color = reds[3]) + 
  geom_text(data = data %>% filter(rank == 1, year == 2016), nudge_x = 0.7, vjust = 1, size = 2.5, aes(label = paste0("T",topic)), color = blues[1]) + 
  geom_text(data = data %>% filter(rank == 2, year == 2016), nudge_x = 0.0, nudge_y = +9*10^3, size = 2.5, aes(label = paste0("T",topic)), color = blues[2]) + 
  geom_text(data = data %>% filter(rank == 3, year == 2016), nudge_x = 0.0, nudge_y = +9*10^3, size = 2.5, aes(label = paste0("T",topic)), color = blues[3])

data <- data[order(rank,decreasing = T)]
bottom.tbl <- data[rank %in% c(1:3,98:100), list(label = label[1], words1995 = words[1] %>% round, words2019 = words[.N] %>% round), by = topic]
bottom.tbl[, change := (words2019 - words1995) %>% round]
bottom.tbl[, percent.change := 100*(words2019/words1995 - 1) %>% round(2)]
bottom.tbl[, percent.change := paste0(percent.change, "%")]
bottom.tbl[, words1995 := formatC(words1995, format="d", big.mark=",")]
bottom.tbl[, words2019 := formatC(words2019, format="d", big.mark=",")]
bottom.tbl[, change := formatC(change, format="d", big.mark=",")]
colnames(bottom.tbl) <- c("Topic", "Label", "Words 1995", "Words 2019", "Abs Change" ,"% Change")

cat("*Panel A: Topics with greatest overall decrease or increase, over sample period*")
p1 %>% print

cat("*Topics with highest increase:*")
bottom.tbl[1:3] %>% kable

cat("*Topics with highest decrease:*")
bottom.tbl[6:4] %>% kable


```

\newpage

**Figure A3**

```{r fig3b, results = "asis", dpi = 300}
int1 <- 2014:2016
int2 <- 2017:2019
lab1 <- "#Words in 2014-2016"
lab2 <- "#Words in 2017-2019"

difgraph <- function(int1, int2, lab1, lab2)
{
  increases <- data[, list(words1 = sum(words[year %in% int1]),
                         words2 = sum(words[year %in% int2])), 
                  by = "topic"]
  increases[, change := words2 - words1]
  setkey(increases, change)
  
  increases$label <- labels[match(increases$topic, labels$Topic)]$ShortLabel
  increases[, label := gsub(" ", "\n", label)]
  
  increases[, rank := 1:.N]
  increases <- increases[rank %in% c(1:3, 98:100)]
  increases[rank %in% 1:3, type := "2. Decrease"]
  increases[rank %in% 98:100, type := "1. Increase"]
  x <- increases
  x[,`:=`(change = round(change), words1 = round(words1), words2 = round(words2))]
  layers <- increases$label[c(6:4,1:3)]
  setkey(increases, rank)
  increases <- increases %>%
  select("topic", "label", "words1", "words2", "type") %>%
  melt(id.vars = c("topic", "label","type")) 


  colnames(increases) <- c("topic", "label", "type" ,"year", "words")
  increases[year == "words1", year := lab1]
  increases[year == "words2", year := lab2]
  increases[, words.text := words %>% round %>% formatC(format="d", big.mark=",")]

  increases$label <- factor(increases$label, levels = layers)

  plot <- increases %>%
    ggplot(aes(x = label, y = words, fill = year)) +
    geom_bar(stat = "identity", position = "dodge") + 
    facet_wrap(~type, scales = "free_x") + 
    th() + theme(axis.title.x=element_blank()) + 
    guides(fill=guide_legend(title="Period")) +
    geom_text(aes(label = words.text, y = words), size = 2.5, position=position_dodge(width=0.9), vjust=-0.25) + 
    scale_fill_brewer(palette = "Paired") + ylab("Number of words") 
  
  #print(plot)
  return(plot)
  #cat("Additional temp table")
  #kable(x)
        
}

cat("*Panel B: Topics with biggest change around 2016 presidential election*")
difgraph(2014:2016, 2017:2019, "#Words in 2014-2016","#Words in 2017-2019") %>% print

cat("*Panel C: Topics with biggest change around 2008-09 financial crisis*")
difgraph(2006:2008, 2009:2011, "#Words in 2006-2008","#Words in 2009-2011") %>% print
```



**Figure A4: Time-series Trends in Agencies**

*Panel A: Agencies with greatest overall decrease or increase, over sample period*

```{r fig4a, results = "asis", dpi = 300}

agencies <- topics.prob.all[, list(words = sum(nwords/Nagencies)), by = "agency,year"]
setkey(agencies, agency, year)
agencies <- agencies[!is.na(agency)]

increases <- agencies[,list(change = (words[.N] - words[1]),
                           years = year[.N] - year[1]), by = agency]

increases <- increases[years == 24]
setkey(increases, change)
increases[, rank := 1:.N]
N <- max(increases$rank)
topagencies <- c(increases$agency[1:3], increases$agency[(N-2):N])

agencies$rank <- increases$rank[match(agencies$agency, increases$agency)]
agencies$label <- mapagency$label[match(agencies$agency,mapagency$agency)]

### add lines
plot <- ggplot(agencies[rank %in% 4:(N-3)], aes(x = year, y = words, fill = "grey")) + 
   geom_line(alpha = 0.5, aes(group = agency), size = 0.1) + 
   geom_line(data = agencies[rank == N], aes(group = agency), size = 0.5, color = reds[1]) +
   geom_line(data = agencies[rank == N-1], aes(group = agency), size = 0.5, color = reds[2], linetype = "dashed") + 
   geom_line(data = agencies[rank == N-2], aes(group = agency), size = 0.5, color = reds[3],linetype = "dotdash") + 
   geom_line(data = agencies[rank == 1], aes(group = agency), size = 0.5, color = blues[1]) +
   geom_line(data = agencies[rank == 2], aes(group = agency), size = 0.5, color = blues[2], linetype = "dashed") + 
   geom_line(data = agencies[rank == 3], aes(group = agency), size = 0.5, color = blues[3],linetype = "dotdash")+ ylab("Words in Federal Register") + 
    th() + theme(axis.title.x=element_blank()) + 
    theme (legend.position = "none") 

### add labels
p1 <- plot + geom_text(data = agencies %>% filter(rank == N, year == 2016), nudge_x = -0.25, vjust = 0, size = 2.5, aes(label = label), color = reds[1]) + 
  geom_text(data = agencies %>% filter(rank == N - 1, year == 2016), nudge_x = 0.0, vjust = 0, size = 2.5, aes(label = label), color = reds[2]) + 
  geom_text(data = agencies %>% filter(rank == N - 2, year == 2016), nudge_x = 0.0, vjust = 0, size = 2.5, aes(label = label), color = reds[3]) + 
  geom_text(data = agencies %>% filter(rank == 1, year == 2016), nudge_x = 0.0, vjust = 0, size = 2.5, aes(label = label), color =  blues[1]) + 
  geom_text(data = agencies %>% filter(rank == 2, year == 2016), nudge_x = 0.0, vjust = 0, size = 2.5, aes(label = label), color =  blues[2]) + 
  geom_text(data = agencies %>% filter(rank == 3, year == 2016), nudge_x = 0.0, vjust = 0, size = 2.5, aes(label = label), color =  blues[3])

       

agencies <- agencies[order(rank,decreasing = T)]
bottom.tbl <- agencies[rank %in% c(1:3,(N-2):N), list(label = label[1], words1995 = words[1] %>% round, words2019 = words[.N] %>% round), by = agency]
bottom.tbl[, change := (words2019 - words1995) %>% round]
bottom.tbl[, percent.change := 100*(words2019/words1995 - 1) %>% round(2)]
bottom.tbl[, percent.change := paste0(percent.change, "%")]
bottom.tbl[, words1995 := formatC(words1995, format="d", big.mark=",")]
bottom.tbl[, words2019 := formatC(words2019, format="d", big.mark=",")]
bottom.tbl[, change := formatC(change, format="d", big.mark=",")]
colnames(bottom.tbl) <- c("Agency", "Label", "Words 1995", "Words 2019", "Abs Change" ,"% Change")

p1 %>% print

cat("*Agencies with highest increase:*")
bottom.tbl[1:3] %>% kable

cat("*Agencies with highest decrease:*")
bottom.tbl[6:4] %>% kable


```

\newpage


```{r fig4b, results = "asis", dpi = 300}

difgraph.agency <- function(int1, int2, lab1, lab2)
{
  increases <- agencies[, list(words1 = sum(words[year %in% int1]),
                         words2 = sum(words[year %in% int2])), 
                  by = "agency,label"]
  increases[, change := words2 - words1]
  setkey(increases, change)


 
  increases[, rank := 1:.N]
  N <- max(increases$rank)
  increases <- increases[rank %in% c(1:3, (N-2):N)]
  increases[rank %in% 1:3, type := "2. Decrease"]
  increases[rank %in% (N-2):N, type := "1. Increase"]
  x <- increases
  #x[,`:=`(change = round(change), words1 = round(words1), words2 = round(words2))]
  layers <- increases$label[c(6:4,1:3)]
  setkey(increases, rank)
  increases <- increases %>%
  select("agency", "label", "words1", "words2", "type") %>%
  melt(id.vars = c("agency", "label","type")) 


  colnames(increases) <- c("agency", "label", "type" ,"year", "words")
  increases[year == "words1", year := lab1]
  increases[year == "words2", year := lab2]
  increases[, words.text := words %>% round %>% formatC(format="d", big.mark=",")]

  increases$label <- factor(increases$label, levels = layers)

  plot <- increases %>%
    ggplot(aes(x = label, y = words, fill = year)) +
    geom_bar(stat = "identity", position = "dodge") + 
    facet_wrap(~type, scales = "free_x") + 
    th() + theme(axis.title.x=element_blank()) + 
    guides(fill=guide_legend(title="Period")) +
    geom_text(aes(label = words.text, y = words), size = 2.5, position=position_dodge(width=0.9), vjust=-0.25) + 
    scale_fill_brewer(palette = "Paired") + ylab("Number of words") 
  
  #print(plot)
  return(plot)
  #cat("Additional temp table")
  #kable(x)
        
}

cat("*Panel B: Agencies with biggest change around 2016 presidential election*")
difgraph.agency(2014:2016, 2017:2019, "#Words in 2014-2016","#Words in 2017-2019") %>% print

cat("*Panel C: Agencies with biggest change around 2008-09 financial crisis*")
difgraph.agency(2006:2008, 2009:2011, "#Words in 2006-2008","#Words in 2009-2011") %>% print
```


```{r drop1prc, fig.width=7.5, fig.height=10}
### source /Users/evolkova/Dropbox/Projects/Govt Agenda/Sandbox/20210812/Drop_1percent.R
require(patchwork)
simulations <- fread("/Users/evolkova/Dropbox/Projects/Govt Agenda/Sandbox/20210812/drop_1percent.csv")

pl <- function(y, xaxis_lab){
  data <- simulations[yvar == y]
  #print(paste0(y, ": real t-stat exceeds simulations in ", sum(data[1:1001]$`t value` > data[1]$`t value`), " out of 1000 iterations |", y, ": real t-stat is below simulations in ", sum(data[1:1001]$`t value` < data[1]$`t value`), " out of 1000 iterations"))
  
  ggplot(data = data[iter > 0]) + 
  geom_histogram(aes(`t value`), bins = 50, color="#000099", fill="lightblue") +
  theme_minimal() + xlab(xaxis_lab) + ylab("Count") + 
  geom_vline(xintercept = data[iter == 0]$`t value`, col = "red")
  
}

pl1 <- pl("lead.sga_at", "T-statistics in SGA/AT regressions")
pl2 <- pl("lead.tfp", "T-statistics in TFP regressions")
pl3 <- pl("lead.roa", "T-statistics in ROA regressions")
pl4 <- pl("lead.growth", "T-statistics in Sales Growth regressions")
pl5 <- pl("lead.growth.at", "T-statistics in Assets Growth regressions")
pl6 <- pl("lead.emp_at", "T-statistics in EMP/AT regressions")


(pl1|pl2) /
(pl3|pl4) /
(pl5|pl6)
```

